language: node_js
node_js:
  - "12"
before_script:
  — npm install -g ionic cordova
script:
  — ionic cordova build browser — prod
deploy:
  local-dir: www
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  on:
    branch: master
notifications:
  email: false
