language: node_js
node_js:
  - "12"
before_script:
  - npm install ionic cordova
  - npm install
script:
  - ionic build
deploy:
  local-dir: www
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  on:
    branch: master
notifications:
  email: false
